
[General]
	#The wooden hoe till range (default while crouching). 0 = 1x1
	#Range: 0 ~ 32
	woodenTierHoeRange = 0
	#The wooden hoe till range (default while crouching). 1 = 3x3
	#Range: 0 ~ 32
	stoneTierHoeRange = 1
	#The wooden hoe till range (default while crouching). 2 = 5x5
	#Range: 0 ~ 32
	goldTierHoeRange = 2
	#The wooden hoe till range (default while crouching). 4 = 9x9
	#Range: 0 ~ 32
	netheriteTierHoeRange = 4
	#Whether the bigger hoe range should only be used if the player is crouching when right-clicking the center block.
	mustCrouchToHaveBiggerHoeRange = true
	#The wooden hoe till range (default while crouching). 2 = 5x5
	#Range: 0 ~ 32
	ironTierHoeRange = 2
	#How much quicker a cropblock (pumpkin/melon) is broken than by default.
	#Range: 0.0 ~ 20.0
	cropBlockBreakSpeedModifier = 8.0
	#When enabled, only allows the un-till function to work when the other hand is empty. Allows placing seeds with hoe in other hand.
	onlyUntillWithOtherHandEmpty = true
	#The wooden hoe till range (default while crouching). 3 = 7x7
	#Range: 0 ~ 32
	diamondTierHoeRange = 3

